url: https://refactor312.github.io/
baseurl: ""

# Site settings
title: Refactor312
email: your-email@domain.com
description: "Write an atsome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."


# Team names, titles and social links
people:

- name: Candice Stauffer, Ph.D.
  pic: CandiceStauffer_Headshot
  position: Executive Director, Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/candicestauffer/
    - title: envelope
      url: mailto:CStauffer@refactor312.org

- name: Eve Chase, Ph.D.
  pic: EveChase_Headshot
  position: Director, Co-Founder
  social:

    - title: linkedin
      url: https://www.linkedin.com/in/evechase/
    - title: envelope
      url: mailto:EChase@refactor312.org

- name: Chase Kimball, Ph.D.
  pic: ChaseKimball_Headshot
  position: Director, Co-Founder
  social:

    - title: linkedin
      url: https://www.linkedin.com/in/chase-kimball-phd-a9a93632/
    - title: envelope
      url: mailto:CKimball@refactor312.org

- name: Monica Rizzo, M.S.
  pic: MonicaRizzo_Headshot
  position: Director, Co-Founder
  social:
    - title: linkedin
      url: https://www.linkedin.com/in/monica-rizzo-921409a3/
    - title: envelope
      url: mailto:MRizzo@refactor312.org


# Build settings
markdown: kramdown
permalink: pretty